version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.1.1
    ports:
      - "8443:8388/tcp"
      - "8443:8388/udp"
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD=nosmokinggoogle
    restart: always
  
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - "9100:9100"
    restart: always
