version: '2'
services:
  human-api:
    domainname: api-human.com
    hostname: api-human
    container_name: api-human
    restart: always
    image: nginx-fcgi:v0
    networks:
      app_net:
        ipv4_address: 172.16.0.122
    ports:
      - "8080:80"
    volumes:
      - /srv/Qylin/universe/project/human/:/var/www/html/

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1   
