version: '2'
services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - "5555:80"
  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nosmoking
    volumes:
      - /Users/qylinqylin/GitBook/Library/qylinfly/docker/share/examples/docker-compose/datadir:/var/lib/mysql
  phpmyadmin:
    external_links:
      - wordpress_db:db
    ports:
      - "5556:80"
    image: corbinu/docker-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=nosmoking
      - MYSQL_USERNAME=root