version: '2'
services:
  wordpress:
    domainname: web-wordpress.com
    hostname: web-wordpress
    container_name: ctr-web-wordpress
    restart: always
    image: wordpress
    links:
      - wordpress_db:mysql
    networks:
      app_net:
        ipv4_address: 172.16.0.20
    ports:
      - "5555:80"

  wordpress_db:
    domainname: web-wordpress-db.com
    hostname: web-wordpress-db
    container_name: ctr-web-wordpress-db
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.0.21
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD:nosmoking

  activemq:
    domainname: web-activemq.com
    hostname: web-activemq
    container_name: ctr-web-activemq
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.0.33
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
      - "5672:5672"
      - "61613:61613"
      - "61614:61614"
    image: rmohr/activemq:5.14.1-alpine
    volumes:
      - /srv/Qylin/data/redis:/data

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1