version: '2'
services:
  web-ngix:
    domainname: web-nginx.com
    hostname: web-nginx-php7
    container_name: ctr-web-nginx-php7
    restart: always
    image: nginx-php7-fpm:ssl
    external_links:
      - ctr-web-mysql
    networks:
      app_net:
        ipv4_address: 172.16.0.6
    ports:
      - "443:443"
      - "80:80"
    environment:
      - DOMAIN=wechat.i-vectors.com
      - WEBROOT=/var/www/html/public
      - GIT_EMAIL=18612116114@163.com
    volumes:
      - /Users/qylinqylin/Project/git-xoxo/project/xoxo/:/var/www/html/

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1   
