version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: wouterm/helloworld
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "5555:80"
    networks:
      - webnet
networks:
  webnet: