version: '2'
services:
  elasticsearch:
    image: linf/elasticsearch-zh:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./esdata:/usr/share/elasticsearch/data

  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - "9100:9100"
    restart: always
